
#project parameters
gcp_project_id=${gcp_project_id}
gcp_temp_location=${gcp_temp_location}
gcp_staging_location=${gcp_staging_location}
gcp_region=${gcp_region}
gcp_network=${gcp_network}
gcp_subnetwork=${gcp_subnetwork}
gcp_pubsub_topic=${gcp_pubsub_topic}
app_name=downstreamupstream
app_name_child=downstreamupstreamchild

# Analytical BUP
analytical_bup.app_name=cdctobigquery
analytical_bup.bucket_url=${analytical_bup.bucket_url}
analytical_bup.topics_prefix=${analytical_bup.topics_prefix}
analytical_bup.subscriptions_prefix=${analytical_bup.subscriptions_prefix}
analytical_bup.prefix_bq_dataset=${analytical_bup.prefix_bq_dataset}
analytical_bup.bucket_schema_root_path_video=${analytical_bup.bucket_schema_root_path_video}
analytical_bup.table_names_video=${analytical_bup.table_names_video}
analytical_bup.max_workers=${analytical_bup.max_workers}

#Secret Manager
gcp_sm_jdbc_database_bup_url=${gcp_sm_jdbc_database_bup_url}
gcp_sm_project_id=${gcp_sm_project_id}
gcp_mongodb_name=${gcp_mongodb_name}
gcp_sm_location=${gcp_sm_location}
gcp_sm_jdbc_user_bup=${gcp_sm_jdbc_user_bup}
gcp_sm_jdbc_user_bup_version=${gcp_sm_jdbc_user_bup_version}
gcp_sm_jdbc_password_bup=${gcp_sm_jdbc_password_bup}
gcp_sm_jdbc_password_bup_version=${gcp_sm_jdbc_password_bup_version}
gcp_sm_jdbc_database_bup=${gcp_sm_jdbc_database_bup}
gcp_sm_jdbc_bup_instance_name=${gcp_sm_jdbc_bup_instance_name}

gcp_sm_jdbc_database_dwh_url=${gcp_sm_jdbc_database_dwh_url}
gcp_sm_jdbc_user_dwh=${gcp_sm_jdbc_user_dwh}
gcp_sm_jdbc_user_dwh_version=${gcp_sm_jdbc_user_dwh_version}
gcp_sm_jdbc_password_dwh=${gcp_sm_jdbc_password_dwh}
gcp_sm_jdbc_password_dwh_version=${gcp_sm_jdbc_password_dwh_version}
gcp_sm_jdbc_database_dwh=${gcp_sm_jdbc_database_dwh}
