#project parameters
gcp_project_id=chrome-coast-348406
gcp_temp_location=gs://artifacts.chrome-coast-348406.appspot.com/temp
gcp_staging_location=gs://artifacts.chrome-coast-348406.appspot.com/temp
gcp_region=us-east1
#gcp_network=https://www.googleapis.com/compute/v1/projects/sha-net-dev-id/global/networks/sha-net-dev-vpc
#gcp_subnetwork=https://www.googleapis.com/compute/v1/projects/sha-net-dev-id/regions/us-east1/subnetworks/subnet-analytics-region-a


#Secret Manager
gcp_sm_project_id=chrome-coast-348406
gcp_mongodb_name=rsantos1089
#projects/chrome-coast-348406/topics/rsantos1089.video.movieDetails
#projects/chrome-coast-348406/subscriptions/rsantos1089.video.movieDetails-sub
# Analytical BUP
analytical_bup.bucket_url=artifacts.chrome-coast-348406.appspot.com
analytical_bup.topics_prefix=projects/chrome-coast-348406/topics/
analytical_bup.subscriptions_prefix=projects/chrome-coast-348406/subscriptions/
analytical_bup.prefix_bq_dataset=analytics_
#analytical_bup.bq_dataset_transactional=ent_dev_bup_analytics_transactional
analytical_bup.bucket_schema_root_path_video=bq_schemas/video/
#analytical_bup.table_names_video=video.movieDetails,video.movieScratch,video.myMovies
analytical_bup.table_names_video=video.myMovies,video.movieScratch
analytical_bup.max_workers=10
