debezium.sink.type=pubsub
debezium.sink.pubsub.project.id=chrome-coast-348406
debezium.sink.pubsub.ordering.enabled=false
debezium.format.value=json
debezium.format.value.schemas.enable=false
debezium.source.connector.class=io.debezium.connector.mongodb.MongoDbConnector
debezium.source.mongodb.ssl.enabled=true
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.mongodb.hosts=rsantos1089-shard-00-00.gvqaq.mongodb.net:27017, rsantos1089-shard-00-01.gvqaq.mongodb.net:27017, rsantos1089-shard-00-02.gvqaq.mongodb.net:27017
debezium.source.mongodb.members.auto.discover=true
debezium.source.mongodb.name=rsantos1089
debezium.source.mongodb.user=m001-student
debezium.source.mongodb.password=pinto1089
#debezium.source.database.include.list=
debezium.source.collection.include.list=video.movieScratch,video.myMovies
debezium.source.time.precision.mode=connect
debezium.source.decimal.handling.mode=string
debezium.source.capture.mode=change_streams_update_full
debezium.source.tombstones.on.delete=true
