debezium.sink.type=pubsub
debezium.sink.pubsub.project.id=chrome-coast-348406
debezium.sink.pubsub.ordering.enabled=false
debezium.format.value=json
debezium.format.value.schemas.enable=false
debezium.source.connector.class=io.debezium.connector.mongodb.MongoDbConnector
debezium.source.database.history=io.debezium.relational.history.FileDatabaseHistory
debezium.source.mongodb.ssl.enabled=true
debezium.source.offset.storage.file.filename=data/offsets.dat
debezium.source.offset.flush.interval.ms=0
#debezium.source.mongodb.hosts=rsantos1089-shard-00-00.gvqaq.mongodb.net:27017, rsantos1089-shard-00-01.gvqaq.mongodb.net:27017, rsantos1089-shard-00-02.gvqaq.mongodb.net:27017
debezium.source.mongodb.hosts=RSANTOS1089/rsantos1089-shard-00-01.gvqaq.mongodb.net:27017,RSANTOS1089/rsantos1089-shard-00-02.gvqaq.mongodb.net:27017,RSANTOS1089/rsantos1089-shard-00-00.gvqaq.mongodb.net:27017
#debezium.source.mongodb.members.auto.discover=true
debezium.source.mongodb.name=rsantos1089
#debezium.source.mongodb.name=cluster0
debezium.source.mongodb.user=<user_mongodb>
#debezium.source.mongodb.user=
debezium.source.mongodb.password=<password_user_mongodb>
#debezium.source.mongodb.password=
#debezium.source.mongodb.authsource=m001-student
debezium.source.tasks.max=3
#debezium.source.database.include.list=
debezium.source.collection.include.list=video.myMovies
#debezium.source.time.precision.mode=connect
#debezium.source.decimal.handling.mode=string
debezium.source.capture.mode=oplog
#debezium.source.capture.mode=change_streams_update_full
#debezium.source.schema.name.adjustment.mode=none
#debezium.source.source.struct.version=v1
debezium.source.transaction.topic=video.transaction
debezium.source.tombstones.on.delete=true
debezium.source.mongodb.delete.on.null.values=true
debezium.source.provide.transaction.metadata=true
#debezium.transforms=unwrap
#debezium.transforms.unwrap.type=io.debezium.transforms.UnwrapFromEnvelope
#debezium.transforms.unwrap.drop.tombstones=false
